name: semnox
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  device_info_plus: ^8.0.0
  dio: ^4.0.6
  easy_splash_screen: ^1.0.4
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.16
  flutter_riverpod: ^2.1.1
  flutter_svg: ^1.1.6
  get_it: ^7.2.0
  intl: ^0.18.0
  json_annotation: ^4.7.0
  loader_overlay: ^2.1.0
  logger: ^1.1.0
  mockito: ^5.3.2
  pretty_dio_logger: ^1.1.1
  retrofit: ^3.3.1

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  retrofit_generator: ^4.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/splash_screen/
