name: semnox
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.23

environment:
  sdk: ">=2.19.6 <4.0.0"

dependencies:
  animated_bottom_navigation_bar: ^1.1.0
  awesome_dialog: ^3.0.2
  badges: ^3.0.2
  barcode_widget: ^2.0.3
  blurrycontainer: ^1.0.2
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  collection: ^1.17.0
  crypto: ^3.0.2
  cupertino_icons: ^1.0.2
  dart_jsonwebtoken: ^2.8.2
  dartz: ^0.10.1
  device_info_plus: ^9.0.2
  dio: ^5.3.3
  document_file_save_plus: ^2.0.0
  dotted_line: ^3.1.0
  easy_splash_screen: ^1.0.4
  equatable: ^2.0.5
  firebase_core: ^2.11.0
  firebase_crashlytics: ^3.2.0
  firebase_messaging: ^14.6.7
  firebase_performance_dio: ^0.5.0
  flutter:
    sdk: flutter
  flutter_carousel_widget: ^2.0.1
  flutter_dotenv: ^5.1.0
  flutter_html: ^3.0.0-beta.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.2
  flutter_otp_text_field: ^1.1.1
  flutter_pdfview: ^1.3.1
  flutter_riverpod: ^2.1.1
  flutter_spinbox: ^0.13.1
  flutter_svg: ^2.0.7
  fluttertoast: ^8.1.2
  freezed_annotation: ^2.2.0
  geolocator: ^9.0.2
  get: ^4.6.5
  glutton: ^2.0.0
  google_fonts: ^4.0.4
  google_maps_flutter: ^2.2.5
  gradient_borders: ^1.0.0
  group_radio_button: ^1.3.0
  in_app_review: ^2.0.6
  infinite_carousel: ^1.0.2
  intl: ^0.18.0
  json_annotation: ^4.8.1
  loader_overlay: ^2.1.0
  loading_indicator: ^3.1.0
  logger: ^1.1.0
  mockito: ^5.3.2
  open_filex: ^4.3.2
  otp_pin_field: ^1.1.2+2
  package_info_plus: ^4.0.2
  path_provider: ^2.0.13
  permission_handler: ^10.2.0
  pretty_dio_logger: ^1.3.1
  qr_flutter: ^4.1.0
  rating_dialog: ^2.0.4
  retrofit: ^4.0.1
  semnox_core:
    path: ../semnox_core
  shared_preferences: ^2.2.0
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.1.14
  uuid: ^3.0.7
  webcontent_converter: ^0.0.8+3
  webview_flutter: ^4.2.2

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  retrofit_generator: ^7.0.1+1

dependency_overrides:
  dio: ^5.3.3
  rive: 0.9.1

flutter:
  uses-material-design: true
  assets:
    - assets/splash_screen/
    - assets/home/
    - assets/login/
    - assets/buy_card/
    - assets/expired_card/
    - assets/localization/
    - assets/lost_card/
    - assets/payment/
    - assets/select_location/
    - assets/card_details/
    - assets/membership/
    - assets/json/
    - .env
